pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'echo "building" >> build.txt'
            }
        }
        stage('Test') {
            steps {
                sh 'ls -la'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying to production'
            }
        }
        stage('Getting sys info') {
            steps {
                sh 'curl ifconfig.me'
            }
        }
    }
}
